# Generated by Django 3.0.7 on 2020-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMultiChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOneChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='TypeQuestions',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='finishD',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='startDate',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'One Choice'), ('2', 'Multi Choice'), ('3', 'Text')], default='3', max_length=128),
        ),
    ]
