# Generated by Django 3.0.7 on 2020-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200624_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hash',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
