# Generated by Django 3.0.7 on 2020-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_person_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerMultiChoice',
        ),
        migrations.DeleteModel(
            name='AnswerOneChoice',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='QuestionId',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='QuestionId',
            field=models.ManyToManyField(to='poll.Question'),
        ),
    ]
