# Generated by Django 3.0.7 on 2020-06-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200624_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='OfferedAnswer',
            new_name='AnswerOption',
        ),
        migrations.RenameField(
            model_name='answeroption',
            old_name='answer_text',
            new_name='answer_option',
        ),
        migrations.RemoveField(
            model_name='person',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.AnswerOption'),
        ),
        migrations.AddField(
            model_name='person',
            name='given_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.GivenAnswer'),
        ),
    ]
