# Generated by Django 3.0.7 on 2020-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200627_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.ManyToManyField(blank=True, null=True, to='poll.AnswerOption'),
        ),
    ]
