# Generated by Django 3.0.7 on 2020-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200627_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='answer_option',
            new_name='option',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=models.ManyToManyField(blank=True, to='poll.AnswerOption'),
        ),
    ]
