# Generated by Django 3.0.7 on 2020-06-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200627_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
    ]
