# Generated by Django 3.0.7 on 2020-06-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20200627_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='given_answer',
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='chosen_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.AnswerOption'),
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Person'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='given_answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
