# Generated by Django 3.0.7 on 2020-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20200627_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hash',
            field=models.IntegerField(default=0),
        ),
    ]
