# Generated by Django 3.0.7 on 2020-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20200627_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='completed_surveys',
            field=models.ManyToManyField(blank=True, to='poll.Survey'),
        ),
    ]
