# Generated by Django 2.2.1 on 2020-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20200627_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='session_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='chosen_answer',
            field=models.ManyToManyField(blank=True, to='poll.AnswerOption'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hash',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
