# Generated by Django 2.2.1 on 2020-07-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20200726_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hash',
        ),
    ]
