# Generated by Django 2.2.1 on 2020-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_remove_person_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='session_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
